### ISSUE TITLE
最近打卡一直不成功

### ISSUE THREAD

**Issue by Mercury-Lamp** [Friedrich-M/AutoDaka#8]
最近打卡的时候钉钉群推送的消息一直是已提交过，实际上却并未打卡，但打开Actions看是成功运行了的
![微信图片_20221017120201](https://user-images.githubusercontent.com/68160576/196088174-b52160dd-34bc-446d-9c24-7294cdd71a2f.jpg)
![微信图片_20221017121709](https://user-images.githubusercontent.com/68160576/196088374-d6a16f71-0329-4b00-9fa3-d59f7abff2bf.jpg)
![屏幕截图 2022-10-17 120123](https://user-images.githubusercontent.com/68160576/196088186-d460c4d6-3361-4b38-90c6-adc87000b6a5.png)

**Comment by Friedrich-M** [comment]
最近有一个pr上来的代码我还没检查就merge了，那个代码应该有问题，我今天修复一下

**Comment by Mercury-Lamp** [comment]
> 最近有一个pr上来的代码我还没检查就merge了，那个代码应该有问题，我今天修复一下

好的，那就麻烦大佬了，谢谢

**Comment by Friedrich-M** [comment]
已修改，请同步最新仓库

**Comment by Mercury-Lamp** [comment]
> 已修改，请同步最新仓库

ok，谢谢大佬
